### ISSUE TITLE
Testing party bug - Timestamp in groupchat for my chat message is inaccurate

### ISSUE THREAD

**Issue by soniasusanto** [gcivil-nyu-org/wed-fall24-team3#140]
Notice timestamp for chat message is few hours ahead of my time.
![Screenshot 2024-11-16 at 4 25 32 PM](https://github.com/user-attachments/assets/feca3761-cca4-43cd-b475-52761e14a303)

**Comment by simarmehta** [comment]
That timestamp is ahead because it based on a specific time zone, although we can make it for every time zone as required but again as I explained during the demo in last class, its one of our latest implementation not completely polished! Can take this up as enhancement not a major bug @soniasusanto
